refactor(overlays): make it easy to disable overlays
rdmorganiser/rdmo pull request #1027
Opened 2024-06-21 15:44 UTC by MyPyDavid

## Description

tried to set `OVERLAYS=None` and that didn't work, so tried to refactor it..
templates would also need be changed for this (if settings.OVERLAYS ...)

Related issue: #ISSUE_NUMBER

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate)

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] I have read the [contributor guide](https://github.com/rdmorganiser/rdmo/blob/main/CONTRIBUTING.md).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-21 15:58 UTC, jochenklar requested changes
I think the working way to disable the overlays is

```
OVERLAYS = {
    'projects': [],
    'project': [],
    'issue_send': []
}
```

but I am not 100% sure.

2024-06-21 15:58 UTC, jochenklar commented on rdmo/overlays/viewsets.py
> +def get_or_create_overlay(user, site, url_name, default_current):
This could be done using https://docs.djangoproject.com/en/5.0/ref/models/querysets/#get-or-create (I should have done this in the first place).

2024-06-21 15:58 UTC, jochenklar commented on rdmo/overlays/viewsets.py
> +def check_overlays_enabled():
Those functions make it actually harder to read the code. Please keep those lines inline. Also, I am very keen on having only ViewSets in viewsets.py and only Views in views.py etc. I usually use utils.py for small helper functions.

2024-08-15 07:51 UTC, closed without merging

2024-08-15 07:51 UTC, MyPyDavid commented
this is not pursued for now