Interview copy dataset
rdmorganiser/rdmo pull request #1128
Opened 2024-08-20 12:59 UTC by jochenklar

This PR adds the possibility to copy tabs (i.e. datasets) or better to create a new tab with all values from the current tab. It works a bit like deleting a set. If a `set_value` is present (e.g. `project/dataset/id`), the catalog is used to get all values for the current set and copy them, along with a new `set_value`. For `#` style sets without attributes this is done in the front end. There is some black magic involved when the `set_prefix` of values is updated with the `set_index` of the new set.

2024-11-08 15:15 UTC, MyPyDavid approved these changes
think it looks good, thanks! 🙏

2025-01-10 14:34 UTC, jochenklar commented
Rebased and good to go.

2025-01-10 14:36 UTC, jochenklar commented on rdmo/projects/assets/js/interview/actions/interviewActions.js
> +          } else {
@MyPyDavid This is complicated, can you check if this is understandable to you. I just fixed a bug here. This front-end part is for copying blocks/questionset (and tabs/pages without attribute).

2025-01-16 09:24 UTC, MyPyDavid requested changes
Overall I think that the current implementation behaves as expected.
I have made only few optional code refactoring remarks.

Somethings about the UX of the tabs of the datasets, they should behave similar to tabs in a browser right? 
* on deleting a dataset, it should activate the one to the right first when it's possible
* for UI design, should the delete icon not be inside of the activated tab? (or on all tabs??) 
* in the delete modal, it should mention the name/label of the tab that will be deleted

During the interview, when applying to all or making the copy, there are multiple requests to `/navigation` and `/progress`. Could this maybe be optimized? I think it calls get requests for each dataset that is updated. Don't know if this could be handled somehow in a single request to each endpoint.

2025-01-16 09:24 UTC, MyPyDavid commented on rdmo/projects/viewsets.py
> +
ok, wanna handle each value maybe in a separate function inside of the `copy_set` method?

```python
    def adjust_set_prefix(value, set_value, set_prefix_length):
        if value.set_prefix == set_value.set_prefix:
            value.set_index = set_value.set_index
        else:
            value.set_prefix = '|'.join([
                str(set_value.set_index) if (index == set_prefix_length) else part
                for index, part in enumerate(value.set_prefix.split('|'))
            ])
        return value
```

2025-01-16 14:49 UTC, jochenklar commented on rdmo/projects/assets/js/interview/actions/interviewActions.js
Makes sense, I just checked with firefox and chrome (how they handle tabs). But deleting the last set should activate the now-last-set aka. C in you example.

2025-01-16 14:53 UTC, jochenklar commented on rdmo/projects/assets/js/interview/actions/interviewActions.js
Which is the case in you code example so, it was probably just a typo in the schenario.

2025-01-16 15:02 UTC, jochenklar commented
I would like to keep the icons where they are, I think it would be to crowded to add all the options to all tabs. (Makes more sense for a browser where you open and close tabs all the time.)

2025-01-16 15:02 UTC, jochenklar commented
I added the name of the tab to the delete modal:

![image](https://github.com/user-attachments/assets/a3812b20-3479-495c-a846-24f8923e5fff)

2025-01-16 15:34 UTC, MyPyDavid commented on rdmo/projects/assets/js/interview/actions/interviewActions.js
ah yes, that was a typo in the scenario sorry, thanks!

2025-01-16 15:38 UTC, MyPyDavid commented
> I would like to keep the icons where they are, I think it would be to crowded to add all the options to all tabs. (Makes more sense for a browser where you open and close tabs all the time.)

this is also fine with me! 👍

2025-01-16 18:17 UTC, jochenklar commented
The remark with the `/progress` opened a can of worms. I now refactored `copyValue` quiet heavily. It now stores all values and then calls `fetchNavigation`, `updateProgress` and checks for a refresh. I think the original version could also been prone to race conditions, since a refresh could be triggered before all values are stored.

2025-01-17 10:26 UTC, jochenklar commented on rdmo/projects/viewsets.py
> +
ok, after some thought, I added a `compute_set_prefix_from_set_value` function for the `else` part. Mainly because I want some parametrized tests for it,

2025-01-17 10:28 UTC, jochenklar commented
I also added 2 small fixes for the bugs we found in yesterdays meeting. Can you check again and approve?

2025-01-17 10:38 UTC, MyPyDavid commented
> I also added 2 small fixes for the bugs we found in yesterdays meeting. Can you check again and approve?

ok great, thanks so much! I'll check it today!

2025-01-17 12:44 UTC, MyPyDavid commented
> The remark with the `/progress` opened a can of worms. I now refactored `copyValue` quiet heavily. It now stores all values and then calls `fetchNavigation`, `updateProgress` and checks for a refresh. I think the original version could also been prone to race conditions, since a refresh could be triggered before all values are stored.

thanks, this looks smooth now!

2025-01-17 12:47 UTC, MyPyDavid commented
Can the range slider also do apply to all? I can't see the icon for it..

And for file uploads, I would guess not right?

2025-01-17 12:48 UTC, MyPyDavid approved these changes
datasets can be copied smoothly now!

2025-01-17 13:16 UTC, jochenklar commented
:pray: 

(the slider works, but it needs a value first)

2025-01-17 14:54 UTC, jochenklar commented
I broke something else, good that we have tests :smirk:

2025-01-17 14:54 UTC, merged

2025-01-17 15:05 UTC, MyPyDavid commented
> I broke something else, good that we have tests 😏

yes, only for all this new interview stuff the front-end (playwright) tests are still missing! 🚨  😉