Feat: add Terms of Use update view and middleware
rdmorganiser/rdmo pull request #1217
Opened 2024-12-18 14:15 UTC by MyPyDavid

## Description

Related issue: #141, #161

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate)

2025-02-03 18:20 UTC, MyPyDavid commented
can be reviewed when tests pass

2025-02-06 07:45 UTC, MyPyDavid commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
As a flow for invalidating the consent (eg. when the text needs an update or the terms changed), 
I thought it would be helpful to be able to simply set this date as a setting instead of manually deleting all of the `ConsentFieldValue` objects. 
Is the name of the `TERMS_VERSION_DATE` ok? Should it be added to the normal core/settings as `TERMS_VERSION_DATE = None` ?

2025-02-06 09:27 UTC, jochenklar requested changes
Great work! I think I will need test it some more with ORCID etc. when we have a release candidate, but I think this approach will work for all.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/middleware.py
> +# these exclude url settings are optional
My philosophy in RDMO was to add all settings to `rdmo.core.settings` in order to avoid those "checking" blocks. (`getattr` is already better than `try ... execpt`.) I suggest we stick to this.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/middleware.py
> +            and request.path != reverse("terms_of_use_accept")
Could be part of `is_path_protected`.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +
Remove newline.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +    @classmethod
I actually likes it better when this was in `utils`. (I just forgot to pull and looked at an older version of the branch.)

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
I like it! And (see my comment above) should have a sensible default (`None`) in `rdmo.core.settings`.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        has_valid_consent = bool(consent and consent.is_consent_valid())
Nitpicking: this `bool` is not needed, is it?

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
Line 166 can be removed.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        # If ISO parsing fails, try localized formats
I wonder if we already use a more generic datetime parsing function in RDMO. If not we should put something like this in `rdmo.core.utils`. Maybe using `datetime.fromisoformat(string)` would suffice.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        # If ISO parsing fails, try localized formats
Ah I see that `parse_date` is already the django version of this.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +from rdmo.core.models import Model as RDMOTimeStampedModel
I am not a fan of renaming in import, but I guess naming it just `Model` was not super clever back then.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +    @classmethod
Ok after looking at it some more, it makes sense together with the other methods.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
Actually I would call it `ACCOUNT_TERMS_OF_USE_DATE` to have some kind of `ACCOUNT_TERMS_OF_USE_` namespacing in the settings.

2025-02-06 09:27 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
Same for the other terms of use related settings.

2025-02-06 09:45 UTC, MyPyDavid commented on rdmo/accounts/models.py
> +    @classmethod
I used the "Fat Models" approach for this and put everything relevant on the model..

2025-02-06 09:49 UTC, MyPyDavid commented
> Great work! I think I will need test it some more with ORCID etc. when we have a release candidate, but I think this approach will work for all.

I think what is still missing is the integration with the social signup form, like the account sign up already has.

2025-02-06 16:12 UTC, MyPyDavid commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
I found now a way to validate a setting via the `from django.core.checks import Error, register`. Do you mind if I add an `rdmo.core.apps.py`  (for the `ready` method) and a `rdmo.core.checks.py` that validates this date string setting?
Im not sure if it's too much or if it could be useful to implement checks also for other settings in this way.

2025-02-07 09:12 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
I would stick to having a default value for the settings used in RDMO (otherwise we are inconsistent in `rdmo`), but something like this could be nice for plugins.

2025-02-07 09:18 UTC, MyPyDavid commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
yes, I mean in addition to setting the default. The default is `None` and then when another value is set, it needs to be a valid to-a-date-parse-able string.

2025-02-07 10:01 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
Hmm, I would not start checking `settings`. If RDMO is misconfigured exceptions will happen. If you mean to check validate the settings *once* when starting and outside of the usage of the settings in the code, I am fine with it. But I don't want to have `validate(settings.FOO_BAR)` everywhere.

2025-02-07 10:16 UTC, MyPyDavid commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
yes, it's exactly that, for `manage.py check`:

```
SystemCheckError: System check identified some issues:

ERRORS:
?: (core.E001) ACCOUNT_TERMS_OF_USE_DATE = 2025-02-36 is not a valid date string.
        HINT: day is out of range for month

System check identified 1 issue (0 silenced).
❯
```

2025-02-07 10:21 UTC, jochenklar commented on rdmo/accounts/models.py
> +        terms_version_date = getattr(settings, 'TERMS_VERSION_DATE', None)
Awesome, go for it.

2025-02-10 17:41 UTC, MyPyDavid commented on rdmo/accounts/socialaccount.py
> +from django.conf import settings
I needed to refactor this to keep the use of `SOCIALACCOUNT` related imports  separate from the normal account imports

2025-02-10 17:42 UTC, MyPyDavid commented on rdmo/accounts/socialaccount.py
> +class SocialSignupForm(AllauthSocialSignupForm, ProfileForm):
this `SocialSignupForm`  is new which Ive added here so that it can be used in combination with the ToU setting

2025-02-10 17:43 UTC, MyPyDavid commented on rdmo/accounts/tests/helpers.py
> +def enable_socialaccount(db, client, settings, django_db_setup, django_db_blocker, django_db_use_migrations): # noqa: PT004
this got a bit messy but I hope now all the tests pass

2025-02-11 14:54 UTC, MyPyDavid commented on rdmo/accounts/tests/helpers.py
> +def enable_socialaccount(db, client, settings, django_db_setup, django_db_blocker, django_db_use_migrations): # noqa: PT004
there were some issue with py38 incompatible style, but we are not using typing anyways..

2025-02-13 14:47 UTC, MyPyDavid commented on rdmo/accounts/tests/helpers.py
> +def enable_socialaccount(db, client, settings, django_db_setup, django_db_blocker, django_db_use_migrations): # noqa: PT004
a fixture that adds an apps and needs migrations (the `allauth.socialaccount`) was not gonna work out.
So we've decided to add it to the initial test config settings `INSTALLED_APPS`, since an added table should not bother the other tests.

2025-02-17 12:17 UTC, jochenklar requested changes
Almost done!

2025-02-17 12:17 UTC, jochenklar commented on rdmo/core/apps.py
> +class AccountsConfig(AppConfig):
This should be `CoreConfig`. I forget to change that also all the time.

2025-02-17 12:17 UTC, jochenklar commented on rdmo/core/apps.py
> +    def ready(self):
The ready function does not need to be here, it should only be added when actually used.

2025-02-17 12:17 UTC, jochenklar commented on rdmo/core/checks.py
> +@register()
This is nice, we should use this more often.

2025-02-17 12:17 UTC, jochenklar commented on rdmo/core/settings.py
> +ACCOUNT_TERMS_OF_USE_MIDDLEWARE = 'rdmo.accounts.middleware.TermsAndConditionsRedirectMiddleware'
I would skip the `ACCOUNT_TERMS_OF_USE_MIDDLEWARE` setting, the middleware needs to be added anyway, we could add it by default. (Did I miss where you did this already?)

2025-02-17 12:17 UTC, jochenklar commented on rdmo/accounts/tests/helpers.py
> +def reload_urlconf(urlconf=None, root_urlconf=None):
In principle the `reload_urlconf` and `reload_urls` could move to a `core.tests.helpers` but we can keep them here for now and move them if we need them again (elsewhere).

2025-02-17 12:17 UTC, jochenklar commented on rdmo/accounts/socialaccount.py
> +from django.conf import settings
Maybe `adapter/account.py` (with imports in `adapter/__init__.py` to keep the existing settings working) and `adapter/socialaccount.py`? Or `adapter_social.py`? In the end its analog to the `adapter.py` file, right? We could also keep `socialaccount.py` if you don't like the suggestions.

2025-02-17 14:13 UTC, MyPyDavid commented on rdmo/accounts/socialaccount.py
> +from django.conf import settings
yes, seems also fine to me. Problem for the name 'adapter' is that there is not only an adapter but also a form in the current `adapter.py` ;)

2025-02-17 14:19 UTC, MyPyDavid commented on rdmo/core/checks.py
> +@register()
yes, should I already refactor into a package `rdmo/core/checks/accounts.py` ?

In another PR, I would also like to add a check for when `DEBUG` is true and the password hasher is not set correctly  :)

2025-02-17 14:27 UTC, MyPyDavid commented on rdmo/core/settings.py
> +ACCOUNT_TERMS_OF_USE_MIDDLEWARE = 'rdmo.accounts.middleware.TermsAndConditionsRedirectMiddleware'
You don't think that there will be a use-case where somebody wants to implement their own middleware for this? Ok, I guess not..

I didn't add it by default to the middlewares yet but seems plausible since the middleware only has an effect with `ACCOUNT_TERMS_OF_USE` enabled, I'll add it then.

2025-02-17 15:45 UTC, jochenklar commented on rdmo/core/checks.py
> +@register()
I would keep it in core for now, technically all `settings` are kind of `core`.

2025-02-17 15:45 UTC, jochenklar commented on rdmo/core/checks.py
> +@register()
And there is a case for `DEBUG` on without the test fixture and real users so ... no.

2025-02-17 15:47 UTC, jochenklar commented on rdmo/core/settings.py
> +ACCOUNT_TERMS_OF_USE_MIDDLEWARE = 'rdmo.accounts.middleware.TermsAndConditionsRedirectMiddleware'
Yes, the one `if` is fine for everybody, and when you want to add your own middleware, you can do so by changing `MIDDLEWARE` what people already need to do for allauth and Shibboleth.

2025-02-17 15:49 UTC, jochenklar commented on rdmo/accounts/socialaccount.py
> +from django.conf import settings
Yes, we could call it `account.py` and `socialaccount.py` and change `settings.py`. I think noone used the filename in their settings.

2025-02-17 16:22 UTC, MyPyDavid commented on rdmo/accounts/socialaccount.py
> +from django.conf import settings
ok, Ive changed it to `account.py`. It can be refactored into a folder when it's needed..

2025-02-18 08:17 UTC, jochenklar commented on rdmo/core/checks.py
> +@register()
no, leave it like it is, we can refactor if the file gets to big. (In daiquiri I moved settings files to all apps btw.).

Yes a warning would be cool.

2025-02-18 08:50 UTC, jochenklar approved these changes
🚂 Awesome, merge! (after tests)

2025-02-18 09:49 UTC, merged