Draft: signal handlers sync project views and tasks
rdmorganiser/rdmo pull request #1218
Opened 2024-12-19 18:34 UTC by MyPyDavid

## Description

Related issue: #ISSUE_NUMBER

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate)

2025-01-09 09:49 UTC, jochenklar requested changes

2025-01-09 09:49 UTC, jochenklar commented on rdmo/projects/tests/test_handlers_tasks.py
> +from .helpers import assert_other_projects_unchanged
I like this. We should stick to `helpers` for tests (and use sparingly) and `utils` for regular code.

2025-01-09 09:49 UTC, jochenklar commented on rdmo/projects/handlers/utils.py
> +
I don't think those methods should exist, this should be inline in the handlers (and without the `getattr`).

2025-01-09 09:49 UTC, jochenklar commented on rdmo/projects/handlers/generic_handlers.py
> +from django.contrib.auth.models import User
I am not sold on this layer of generic handlers, but lets talk about this in the meeting. Maybe custom project signals would be better?

2025-01-20 16:53 UTC, MyPyDavid commented on rdmo/projects/handlers/utils.py
> +
I could make it more explicit but it would require a lot more boilerplate code. 
The signal handlers for `View` and `Task` are basically duplicates, so there would be 18 branches instead of the 9 `if action == ...` in total in the different functions for `.catalogs`, `.sites` and `.groups` .
But we already agreed about this in the meeting right?

Or would there be an extra use case that would require an update on the Issues as well, when project.tasks are handled?


Example for an explicit function
```py

    # Identify the catalogs affected by this change
    catalogs = model.objects.filter(pk__in=pk_set)

    # Determine the projects to be modified
    if action == 'post_add':
        projects = Project.objects.filter_catalogs(catalogs).exclude(views=instance)
        for project in projects:
            project.views.add(instance)

    elif action == 'post_remove':
        projects = Project.objects.filter_catalogs(catalogs).filter(views=instance)
        for project in projects:
            project.views.remove(instance)

    elif action == 'post_clear':
        projects = Project.objects.filter(views=instance)
        for project in projects:
            project.views.remove(instance)
 ```

2025-01-22 09:52 UTC, MyPyDavid commented on rdmo/tasks/managers.py
> +    def filter_available_views_for_project(self, project):
I think that a `Project` should be able to find the `views` that are available for itself. Do you agree and would this query be correct for that?
I've changed the `filter_group` a little bit to handle a list of `users` as well as a single `user`.

2025-01-22 09:53 UTC, MyPyDavid commented on rdmo/projects/forms.py
> +        # if the catalog is the same, do nothing
I tried to prevent calling the `save` method if nothing was changed

2025-01-22 09:56 UTC, MyPyDavid commented on rdmo/projects/handlers/project_save_tasks.py
> +    setattr(instance, DEFERRED_SYNC_TASKS_KEY, True)
I needed a `pre_save` to check if the `catalog` was changed or not. And afterwards it passes this boolean (with deferred name) to the `post_save`.
It seems complicated for just a `project.save()` but could not find another way.

2025-01-22 09:58 UTC, MyPyDavid commented on rdmo/projects/tests/helpers.py
> +                    'sites': list(view.sites.values_list('id', flat=True)),
I wanted to explicitly test this filter `filter_available_views_for_project` with this mapping but have not implemented that test yet.

2025-02-06 10:37 UTC, MyPyDavid commented on rdmo/tasks/managers.py
> +    def filter_available_views_for_project(self, project):
this kind of method is also needed for an endpoint (for project.views) in the new Project Detail in React I think

2025-02-06 11:25 UTC, jochenklar commented on rdmo/tasks/managers.py
> +    def filter_available_views_for_project(self, project):
As discussed in the meeting.

2025-02-06 11:43 UTC, MyPyDavid commented on rdmo/projects/forms.py
> +        if 'cancel' in self.data:
need to check again, if this was needed or not (cancel seems to work already)

2025-02-06 11:46 UTC, MyPyDavid commented on rdmo/projects/handlers/project_save_tasks.py
> +    setattr(instance, DEFERRED_SYNC_TASKS_KEY, True)
remove setattr and just use, eg. `instance._catalog_has_changed_sync_task`

2025-02-14 11:04 UTC, MyPyDavid commented on rdmo/projects/templates/projects/project_detail_issues.html
> +                {% if can_change_project and not settings.PROJECT_TASKS_SYNC  %}
So, I am adding now a filter to the managers that is used for all cases where a project needs its available views/tasks.
There is no request.user in the loop anymore. Is that a problem? The filter is determined by the project's properties (like `project.site, `.catalogs` and the new `.groups` )

```py
    def filter_available_views_for_project(self, project):
        site_filter = Q(sites=project.site) | Q(sites__isnull=True)
        catalogs_filter = Q(catalogs=project.catalog) | Q(catalogs__isnull=True)
        groups_filter = Q(groups__in=project.groups) | Q(groups__isnull=True)
        availability_filter = Q(available=True)
        return self.filter(site_filter & catalogs_filter & groups_filter & availability_filter)
```

2025-02-14 12:51 UTC, MyPyDavid commented on rdmo/projects/apps.py
> +        if settings.PROJECT_VIEWS_SYNC:
yes, I created a regular package (python folder) for the handler related modules, I would keep enabling sync tasks and views separate since they are independent features.

2025-02-14 13:03 UTC, MyPyDavid commented on rdmo/projects/forms.py
> +        if 'cancel' in self.data:
yeah, it's not needed, `save()` is not called when "Cancel" is in request, I'll revert it.

2025-02-14 13:34 UTC, MyPyDavid commented on rdmo/core/settings.py
> +PROJECT_TASKS_SYNC = True
should these actually be enabled by default?

2025-02-14 13:51 UTC, MyPyDavid commented on rdmo/projects/forms.py
> +    def save(self, commit=True, *args, **kwargs):
yes, but it might be just an optional optimization, think I'll remove it again for now.

2025-02-14 13:58 UTC, MyPyDavid commented on rdmo/projects/handlers.py
> +    # remove views that are no longer available
yes, I've added that check now to the `projects/handlers/project_save_views.py` and `project_save_tasks.py` by using the `pre_save` and `post_save` signals

2025-02-14 13:58 UTC, MyPyDavid commented on rdmo/projects/handlers.py
> +                                #   .filter_group(self.request.user) \
this whole module will be removed

2025-02-14 14:00 UTC, MyPyDavid commented on rdmo/projects/handlers/generic_handlers.py
> +    """
ok, it's nice when they are auto-generated and correct but so far we don't have them in the code base anyways so I removed the docstrings again.

2025-02-14 15:26 UTC, MyPyDavid commented
rebased to 2.3.0

2025-02-17 12:41 UTC, jochenklar requested changes
The main issue is about the new managers and availability. An reviewer/editor/admin should be able to assign a non available Task/View to a project to test it.

2025-02-17 12:41 UTC, jochenklar commented on rdmo/core/settings.py
> +PROJECT_TASKS_SYNC = True
I think not.

2025-02-17 12:41 UTC, jochenklar commented on rdmo/views/managers.py
> +        return self.filter(site_filter & catalogs_filter & groups_filter & availability_filter)
I am sorry but there is a newline in `rdmo.tasks.managers` right here :upside_down_face:

2025-02-17 12:41 UTC, jochenklar commented on testing/config/settings/base.py
> +PROJECT_VIEWS_SYNC = True
Depending on the default settings and the tests, maybe this should be False (or removed from this file).

2025-02-17 12:41 UTC, jochenklar commented on rdmo/tasks/managers.py
> +        availability_filter = Q(available=True)
I think you removed the check for the managers and admins here, this was done by `.filter_availability(self.request.user)` and needs the user. This comes from `AvailabilityQuerySetMixin`. I think you also reimplemented the other thinks in `core/managers.py`.

2025-02-17 12:41 UTC, jochenklar commented on rdmo/tasks/managers.py
> +        availability_filter = Q(available=True)
Maybe the availability part should stay in `AvailabilityQuerySetMixin` and we need only `filter_for_project` and use it like this 

```python
tasks = Task.objects.filter_for_project(project).filter_availability(self.request.user)
```

alternatively 3 methods

```
        tasks = Task.objects.filter_for_project_site(project) \
                            .filter_for_project_catalog(project) \
                            .filter_for_project_group(project) \
                            .filter_availability(self.request.user)
```

2025-02-18 08:57 UTC, jochenklar commented on rdmo/tasks/managers.py
> +        availability_filter = Q(available=True)
I like "my" style better, but I think this is fine (at least no `\`). I would indent the two '.filter...' lines by 4.

2025-02-20 12:23 UTC, MyPyDavid commented on rdmo/tasks/managers.py
> +        availability_filter = Q(available=True)
I've used one-liner queries when there is only a single filter and it fits on one line, for multiple filters I've used this multi-line parentheses notation with the extra indent. So basically best of both worlds ;)

2025-02-20 12:24 UTC, jochenklar approved these changes
Done, thanks!

2025-02-20 12:32 UTC, merged