Rewrite interview using React and Redux
rdmorganiser/rdmo pull request #941
Opened 2024-03-12 17:14 UTC by jochenklar

This PR *will* add a new React/Redux based interview, which replaces `project_questions`. It will also remove the vendor file system and django-compressor/SASS. So far the following changes are implemented:

* Add project_interview view
* Refactor webpack config

2024-06-28 10:11 UTC, CalamityC requested changes

2024-08-25 12:07 UTC, jochenklar commented on rdmo/core/assets/js/components/Modal.js
I use the Modal in `2.3.0` and refactored a bit, but it should still work with `projects`.

2024-08-25 12:07 UTC, jochenklar commented on rdmo/core/assets/js/hooks/useModal.js
I updated my branches accordingly.

2024-08-25 12:08 UTC, jochenklar commented on rdmo/core/assets/js/utils/lang.js
I created a `meta.js` with all html `<meta>` parsing functions and refactored everything so that it still works.

2024-12-05 16:18 UTC, MyPyDavid commented on rdmo/projects/assets/js/interview/components/main/Breadcrump.js
maybe rename to `Breadcrumb.js` ;)

2024-12-05 16:48 UTC, MyPyDavid approved these changes
thanks for all the work!

2024-12-06 08:24 UTC, jochenklar commented on rdmo/projects/assets/js/interview/components/main/Breadcrump.js
Yes, I will do so at the end.

2024-12-06 08:24 UTC, merged